### ISSUE TITLE
[Feature] Add more Booru APIs

### ISSUE THREAD

**Issue by fleurc** [khoadng/Boorusama#333]
**Is your feature request related to a problem? Please describe.**
While the app is extremely good and works well, there is a lack of support for certain APIs that competitors like Loli Snatcher provide. It is a very strong contender for me, but thanks to the lack of APIs available I cannot have all my favorite boorus accessible.

**Describe the solution you'd like**
Try to look at the API list of Lolisnatcher and find a way to implement in future an equivalent API list for more Booru access.

**Describe alternatives you've considered**
My alternative here would be to slowly add the APIs that are listed, starting with whatever APIs are easier to get to, or the APIs that I need atm.

The booru APIs that I use:
- [X]  Danbooru
- [X]  e621
- [X]  Gelbooru
- [ ]  Sankaku
- [ ]  Philomena
- [ ]  Shimmie
- [ ]  GelbooruV1

**Additional context**
APIs that Loli Snatcher has Access to:

https://files.catbox.moe/6y8p0p.jpg

https://files.catbox.moe/9vfisa.jpg

https://files.catbox.moe/geh1ob.jpg

An addendum, sometimes the automatic detection doesn't detect the correct Booru, such as with hypnohub being said that it likely won't work when it uses the same exact API as Gelbooru.

**Comment by khoadng** [comment]
Thanks for opening the issue!

The app originally began as a Danbooru client, resulting in a patchwork approach to support other sites. The architecture is a bit disorganized, and I've been working on its restructuring for some time now.

I don't really use Gelbooru a whole lot. Do you have an example site for Gelbooru V1? I thought Gelbooru V1 didn't support APIs?

**Comment by fleurc** [comment]
The ones I use which use GelbooruV1 are:

https://captions.booru.org/

And

https://joi.booru.org/

I know the API for these is GelbooruV1 because Lolisnatcher tells me so.

**Comment by khoadng** [comment]
Oh, I see. They simply crawl the site and manually parse the HTML.
I'll add support for those sites once I'm done with the restructuring

**Comment by fleurc** [comment]
Thank you!

**Comment by khoadng** [comment]
I added some basic support for those APIs. Just need a bit testing. 
If you want to try it out, join my discord. I've uploaded an experimental version there.

**Comment by fleurc** [comment]
Have downloaded the new APK and am testing, for now it seems to work perfectly well and as intended. Will test the GelbooruV1 boorus on Masonry to see what their specific glitchiness is too.

**Comment by khoadng** [comment]
Implemented in 3.5.0. You can download it from the store.
