### ISSUE TITLE
[Bug] Hypnohub doesn't tag properly on Gelbooru API

### ISSUE THREAD

**Issue by fleurc** [khoadng/Boorusama#343]
**Describe the bug**
When searching tags on Hypnohub on Gelbooru (Not V1 or V2) the Tagging system breaks down and gets "stuck" with whatever tags were previously seen.

**To Reproduce**
1. Add [Hypnohub](https://hypnohub.net/)
2. Click on an image
3. See tags
4. Swipe to next Image
5. See bug (Tags not changing)

**Expected behavior**
Tags switching from image to image.

**Screenshots**

[Screenshot 1](https://files.catbox.moe/btwsze.jpg)

[Screenshot 2](https://files.catbox.moe/cl1ypk.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung A73
 - OS: Android 13
 - Version app: 3.5.0

**Additional context**
Switching to Gelbooru V2 fixes the problem. This only happens in Gelbooru API not V1 or V2.

**Comment by khoadng** [comment]
Gelbooru API is intended for use with Gelbooru, I will remove it from the options in future version.

**Comment by fleurc** [comment]
Ok

**Comment by khoadng** [comment]
Fixed in 3.5.1
