### ISSUE TITLE
[Bug] AI Booru doesn't show fullres image

### ISSUE THREAD

**Issue by fleurc** [khoadng/Boorusama#344]
**Describe the bug**
When clicking on top of images they don't load as full images. Only loads thumbnails.

**To Reproduce**
1. Add [AI Booru](https://aibooru.online/)
2. If asked set the API to Danbooru
3. Click on any image
4. See bug.

**Expected behavior**
That full sized images would load.

**Screenshots**
[Expectation (Danbooru)](https://files.catbox.moe/ouhur9.jpg)
[Reality (AI booru)](https://files.catbox.moe/2pnifk.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung A73
 - OS: Android 13
 - Version app: 3.5.0

**Additional context**
This is not an API problem.

**Comment by khoadng** [comment]
It seems they've recently changed their API. I'll take a look.

**Comment by khoadng** [comment]
Fixed in 3.5.1
