### ISSUE TITLE
Different quality depending on network

### ISSUE THREAD

**Issue by viperML** [khoadng/Boorusama#369]
**Is your feature request related to a problem? Please describe.**
Being able to preview images at highrst quality when I'm connected to wifi (or unmetered network), and change to another when not, like low.

**Describe the solution you'd like**
The current quality setting to be split in two, maybe.

**Describe alternatives you've considered**
n/a

**Additional context**
To not consume much data from my data plan by accident.

**Comment by khoadng** [comment]
How about adding a banner at the top of the image list to alert you when high-quality images are being displayed without a Wi-Fi connection? This banner could offer a convenient button to adjust the current image quality and be easily dismissible.

**Comment by viperML** [comment]
But then, when you come back to a wifi connection, it would still be on the lower quality setting?

**Comment by khoadng** [comment]
Yeah, since the button in the banner will update the currently selected quality in settings, I'd prefer not to add a new option to the settings as it might be a bit complicated for the average user.

**Comment by viperML** [comment]
I understand, and I also don't want to add into the "feature creep". Feel free to close the issue or leave it open....

**Comment by khoadng** [comment]
I'll go ahead and add the banner. It's a simple enough solution and still somewhat solves your problem (not consuming much data plan by accident)

**Comment by khoadng** [comment]
<img width="150" alt="Screenshot 2024-01-25 at 23 27 40" src="https://github.com/khoadng/Boorusama/assets/19619099/6df2f9f4-c892-4b7b-9a3c-016dff6ab5ba">

This banner will only show up when the selected settings are set to high and highest on mobile network.
