### ISSUE TITLE
[FR] Isolate each booru's favorite searches

### ISSUE THREAD

**Issue by ciel-d-automne** [khoadng/Boorusama#371]
**Is your feature request related to a problem? Please describe.**
As of now favorite searches are global.

**Describe the solution you'd like**
Make searches favorited when browsing Safebooru (e.g.) only visible when Safebooru is selected, hide them when browsing Gelbooru (e.g.)

**Comment by khoadng** [comment]
Some users might prefer having a single list of favorite searches for every site. How about adding a filter dropdown, similar to the one on the bookmark page? A new screen for users to handle favorite searches is probably needed as well
