### ISSUE TITLE
View original image / gif by default upon opening it

### ISSUE THREAD

**Issue by MrShiruba** [khoadng/Boorusama#395]
**Is your feature request related to a problem? Please describe.**
When you touch / open an image or a GIF that is large / big (I think bigger than 1000x1000) on a browser on for example rule34.xxx or gelbooru.com, the site displays a smaller version of the image / first frame for a gif and shows a message "This image has been resized. Click here to view the original image. Always view original. Don't show this message." for rule34 and "Click here to expand image." for gelbooru to have the original image or have the animated gif. 

In the case of Boorusama, it is always the smaller version / first frame of the gif that is displayed. You can't have the looping gif unless you go to the three dots menu and choose "View original". Except the loading of the gif takes some seconds (I think because of the API).

**Describe the solution you'd like**
The gif is directly loaded upon touching it, with "minimal" loading times. It can be switched with an option in "Settings > Performance" with something like "Large Image behaviour" with 2 options :
- Show preview image (current behaviour)
- Show original image (with some text showing "This may increase loading time")

**Describe alternatives you've considered**
Reduce the loading time to display the original GIF (if possible). Otherwise converting the GIF to WEBM but I don't know if making a video without a common ratio aspect (16:9, 9:16...) is a good idea.

**Additional context**
Examples gifs (both are NSFW and I've added a space after the ":" in case of bots) : https: //rule34.xxx/index.php?page=post&s=view&id=9423110 and https: //gelbooru.com/index.php?page=post&s=view&id=7569089

**Comment by khoadng** [comment]
You can long press a profile to open up its settings and tweak it to your liking. These settings are specific to each profile cause every site's got its own quirks.
<img width="317" alt="Screenshot 2024-04-01 at 08 26 12" src="https://github.com/khoadng/Boorusama/assets/19619099/9bc2c70e-025b-4dba-ab96-7d624dc74c51">

**Comment by MrShiruba** [comment]
Actually I just found that the feature is already implemented :
Go to your profile > Edit > Gestures > Image Preview, Tap > View original.
