### ISSUE TITLE
Easier app navigation

### ISSUE THREAD

**Issue by GitGitu79** [khoadng/Boorusama#397]
**Is your feature request related to a problem? Please describe.**
Having to go to the hamburger menu at the very far top left corner to open a sidebar is painful and uncomfortable. 

Every mean of navigation is on the sidebar, so if I want to do anything I have to go to this corner. This especially becomes a problem with one-handed use.

Also the placement of booru profile, that thing is even further to the left than the hamburger menu, so if I want to quickly switch to another booru it becomes even more frustrating

**Describe the solution you'd like**
1. Swipe gesture to open a sidebar (https://github.com/NO-ob/LoliSnatcher_Droid) or it can be a setting where the user can set the amount of screen area to trigger a swipe (https://github.com/jiangtian616/JHenTai)

2. Make it floating action button and put it at the bottom right

3. Put the entire search bar to the bottom (https://github.com/nullxception/boorusphere). In fact this can go even further by making another button in the search bar where it can be used as a booru selection

Any change that makes it not focused on the top left corner is fine by me

**Describe alternatives you've considered**
All the app in the solution

**Additional context**

**Comment by khoadng** [comment]
What is your device model and Android version? I can swipe to open the sidebar just fine on my device (Xiaomi 11, Android 13)

**Comment by khoadng** [comment]
The gesture navigation maybe vendor specific then, I never use gesture navigation so I don't know. 
 > a setting where the user can set the amount of screen area to trigger a swipe 
 This seems like the best solution, you can increase the swipe area to prevent conflict with system navigation however this might conflict with page swipe gesture in pagination mode

**Comment by khoadng** [comment]
Solution 3 might be also good for people who only have a few profiles. 

Quick prototype

https://github.com/khoadng/Boorusama/assets/19619099/57f75edf-805f-4477-b13c-e0e41b71f5d2

**Comment by khoadng** [comment]
So here is what going to be updated:
- A new accessibility settings screen
- A new option to adjust the swipe area that trigger a swipe to open the sidebar
- A new option to reverse the scroll direction of booru profile for one-handed use, maybe useful for people only having less than 5 profiles.
- A new option to change the placement of booru profile
