### ISSUE TITLE
The biometrics lock does absolutely nothing.

### ISSUE THREAD

**Issue by Samscryption** [khoadng/Boorusama#400]
**Describe the bug**
First of all, you can see the posts in the background before you even start interacting with the password field.
And worst of all, you can just tap on "cancel" and, instead of closing the app, it just lets you use the app normally. 
Like it never needed a password.

**To Reproduce**
1. Go to the privacy settings and have biometrics lock on.
2. Open the app
3. Instead of bothering to put the password just click on cancel
4. Now you can use the app normally

**Expected behavior**
The app should be closed and unable to be accessed until the biometrics have been completed.

**Screenshots**
Unable to take one as the biometrics screen prevents you from taking screenshots

 Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab A7 Lite
 - OS: Android 14
 - Browser Google Chrome
 - Version 3.13.1 (Google play store)

**Additional context**
Having an option for secure screen would be good

**Comment by khoadng** [comment]
Could you head over to `Settings > Debug logs` and copy/paste or upload the log here? Just make sure you do it with an anonymous profile to keep your info private

**Comment by Samscryption** [comment]
> Could you head over to `Settings > Debug logs` and copy/paste or upload the log here? Just make sure you do it with an anonymous profile to keep your info private

![Screenshot_20240412_104113_Boorusama.jpg](https://github.com/khoadng/Boorusama/assets/116762353/6150ddf2-a386-4183-b05c-b552697c0f7e)

**Comment by khoadng** [comment]
Technically, a password lock isn't a biometric one, so the app doesn't stop users from just getting right in. I'll try to sort this out, but the tricky part is, I don't have a device with just a password lock to test it.
