### ISSUE TITLE
Blur explicit materials in search results

### ISSUE THREAD

**Issue by User8388493929** [khoadng/Boorusama#406]
**Is your feature request related to a problem? Please describe.**
Explicit content can either be fully visible or filtered completely from search results, there is no option in between.

**Describe the solution you'd like**
Adding an option to blur explicit materials under the "content filtering" setting in the profile menu with the same options like "None, Aggressive" etc.

**Additional context**
This feature was inspired by the content blurring option of the "Boorusphere" application:
![Screenshot_20240422-130540_Boorusphere](https://github.com/khoadng/Boorusama/assets/166151037/5b62bf4f-bf68-4520-8643-0a08f007f714)

**Comment by khoadng** [comment]
Can you tell me why you need this option in the first place? If you want to browse explicit content create a new profile that enable it. This is by design.

Also the "content filtering" in the profile settings is done server-side, so if something's not there, the app can't blur it.

**Comment by User8388493929** [comment]
Because using a separate profile just for filtering or viewing NSFW content isn't convenient. I would have to choose one of the profiles to use based on whether I'm OK with adult content at the moment or not, and even then my current mood could change anytime.

Blurring gives the user freedom to either get exposed to view NSFW content intentionally or ignore it, while being aware of it's existence. It'a great balance between viewing explicit content and being protected against it.
I would also like to mention that many big media-based platforms like twitter and reddit, and an already existing booru application has a feature like this and I find all of them to be useful.

For the options part; I only meant the selection that could be presented to the user, implementation can be done client-side.

This is not a killer feature, I can use workarounds. But such an option is more practical than creating a new profile in my opinion.

**Comment by User8388493929** [comment]
I understand, thanks for considering. 

And no, not really. I presented it as a profile setting at that moment, global sounds better.
