### ISSUE TITLE
Konachan not connecting

### ISSUE THREAD

**Issue by CreativeC0der** [khoadng/Boorusama#411]
![Uploading Screenshot_20240504-113521_Boorusama.jpg…]()
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CreativeC0der** [comment]
[boorusama_logs.txt](https://github.com/khoadng/Boorusama/files/15208131/boorusama_logs.txt)

**Comment by khoadng** [comment]
konachan is putting their API behind a Cloudflare's browser check, which i'm not sure how to deal with when you're using an app

**Comment by CreativeC0der** [comment]
Flexbooru has done it somehow...Maybe consult their code
