### ISSUE TITLE
Favorite button is missing with Gelbooru

### ISSUE THREAD

**Issue by SNS47** [khoadng/Boorusama#418]
**Describe the bug**
There is only bookmark button, but no favorite button when using Gelbooru. Not only that, I found that there's no way to favorite an image. At the "gestures" tab under Gelbooru's booru profile editing page, all of the gestures dropdowns only show: none, download, save, share, toggle bookmark, view tags, view original, and open source (no favorite option).

**To Reproduce**
1. Open app
2. Create a new booru profile (swipe from left edge of screen to right and then click the plus shaped button)
3. Enter https://gelbooru.com/
4. Enter User ID and API Key found in user's Gelbooru profile
5. Press OK
6. Switch the app's profile from the default Danbooru to Gelbooru
7. Click on any image
8. The button to favorite the image is missing. There are only bookmark, download, comment, and share buttons.

**Expected behavior**
The button to favorite the image should be present.

**Screenshots**
Gelbooru: 
![Gelbooru Buttons](https://github.com/khoadng/Boorusama/assets/171399110/d1f8e55f-f217-443a-80d4-c706d459fd53)
Danbooru:
![Danbooru Buttons](https://github.com/khoadng/Boorusama/assets/171399110/efffb17e-233a-45da-9c65-774f87a8cae8)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy J3 Pro
 - OS: Android 9
 - Browser: Brave browser for getting the API, Boorusama for viewing the Gelbooru
 - Version: Boorusama version 3.16.0
 - Gelbooru API Version: 0.2.5

**Comment by khoadng** [comment]
Gelbooru's API does not provide that functionality.

See [docs](https://gelbooru.com/index.php?page=wiki&s=view&id=18780)
