### ISSUE TITLE
Download buttons

### ISSUE THREAD

**Issue by Seresuta** [khoadng/Boorusama#423]
While viewing an image, the download icon at the bottom registers a tap, but does not download image. When opening the options menu in the top right and tapping download, it registers the tap and closes the menu, but does now download the image. The only way I have found to successfully download an image was by using the menu to view in browser.

**Comment by khoadng** [comment]
What site are you using? Are you set up a custom download location or just use the default?

**Comment by Seresuta** [comment]
I am using the app from Google play store

Thank You

Chris Storz
email: ***@***.***
Phone: 972-977-6738
Text: 972-977-6738

**Comment by Seresuta** [comment]
Sorry, I misunderstood the question. I have been using the app for a week
with default settings on Gelbooru without issue. Today was the first time
the download buttons did not work

Thank You

Chris Storz
email: ***@***.***
Phone: 972-977-6738
Text: 972-977-6738

**Comment by khoadng** [comment]
Make sure you don't have the ignore downloaded files option turned on.

**Comment by Seresuta** [comment]
Should I use Legacy?

Thank You

Chris Storz
email: ***@***.***
Phone: 972-977-6738
Text: 972-977-6738

**Comment by Seresuta** [comment]
Nevermind, legacy doesn't work either

Thank You

Chris Storz
email: ***@***.***
Phone: 972-977-6738
Text: 972-977-6738

**Comment by khoadng** [comment]
Can you check the download button on the context menu in the image list?

**Comment by Seresuta** [comment]
That one isn't working either. Neither button for downloads works in the
current manager or the legacy one. I started trying to troubleshoot by
clearing my cache and have done everything I could think of. Was there a
change made in the last 24 hours?

Also, forgot to mention, I am on an up to date S20 Ultra

Thank You

Chris Storz
email: ***@***.***
Phone: 972-977-6738
Text: 972-977-6738

**Comment by khoadng** [comment]
I changed a lot of things related to downloading, so something might be broken. Can you set a custom download location and see if it works?

**Comment by Seresuta** [comment]
Results:

I set a user specified save location and tested each button on different
images for both legacy and new manager. All 4 images downloaded
successfully, but the pop-up that says download started did not appear for
any of them. So it does function if I set the destination folder, but
doesn't give any indication that it started the download. Have to go into
my file system and verify.

Thank You

Chris Storz
email: ***@***.***
Phone: 972-977-6738
Text: 972-977-6738

**Comment by khoadng** [comment]
I see the issue now. Thanks for reporting.

**Comment by Seresuta** [comment]
Absolutely! I was so happy to find your app when onlymash completely
changed Flexbooru. Your app works better than his did before he changed it.
I am off to bed for the night, but I look forward to continuing to use your
app for the foreseeable future. Thank you so much for creating it the way
you did!

Thank You

Chris Storz
email: ***@***.***
Phone: 972-977-6738
Text: 972-977-6738
