### ISSUE TITLE
Swiping works abysmally tablet

### ISSUE THREAD

**Issue by IggyI** [khoadng/Boorusama#425]
I'm not sure what is causing this, other apps and viewers works just fine, and this one works great on my phone, however on my galaxy tab s9 ultra, you need to swipe with extreme percision. About 80% of my swipes simply don't register. To get more to register I need to swipe extactly from the middle and directly left or right, without so much as a 5 degree angle. I don't know if it's on all tablets or just mine. Forced to basically use the arrows, which is far from ideal on a tablet.

**Comment by khoadng** [comment]
What screen are you referring to? There are many swipe gestures within the app, so please be more specific

**Comment by IggyI** [comment]
When you enter the app, and click on any image, when you want to see the next image, swiping works very poorly on a large tablet, arrow buttons work just fine.

**Comment by khoadng** [comment]
Landscape or portrait mode? I don't remember enabling swiping on that screen for the tablet.

**Comment by IggyI** [comment]
Both, landscape or portait, swiping hardly registers. It works, like one out of 10 swipes do register, or If I try very hard and concentrate the swipe might register.

**Comment by khoadng** [comment]
Just tested it on my tablet, I can't swipe at all, not sure how you can even swipe to begin with. Can you send a recording?

Also, the UI for the tablet is actually designed for desktop, so things are not well optimized.

**Comment by IggyI** [comment]
Okay, I could swipe before horizontally a little because that's how I prefer to use it, now horizontal doesn't work at all, but vertical does and it's not that bad, most swipes register if they are very horizontal.

[Boorusama Swiping Test](https://youtu.be/pDTOWEJZ0N8)
[Boorusama Taskbar Element Test](https://youtu.be/QbkH-S8NxBs)

I do like the UI on the big screen, and the fact that previews are actually really high quality (most viewers fail in the regard) really helps.

**Comment by khoadng** [comment]
Thanks for the videos.

For the divider button, I will make the touch area bigger.

Swiping in landscape mode is tricky because the app uses a big screen layout designed for desktop. Creating a separate layout for tablets would be a pain to maintain in the long run, so it won't be supported for now.

**Comment by IggyI** [comment]
How bad does the layout intended for phones look like? Any chance of a setting to force phone layout (assuming it looks half decent)?

**Comment by khoadng** [comment]
There is already a option to force desktop or mobile layout in the development environment of the app, but it is still rough around the edges. I will push it to production when I'm happy with how it looks.
