### ISSUE TITLE
Items drawn behind android nav bar 

### ISSUE THREAD

**Issue by thebrokenfacade** [khoadng/Boorusama#426]
**Describe the bug**
Some items are rendered underneath the nav bar on my tablet in landscape a portrait mode. By under, I mean a lower layer, not an x-y coordinate location. Like the menu you get from swiping down from the top of the screen (quick settings, notifications, etc.) draws over whatever app you have open. This prevents the user from interacting with the items as they are obscured by the nav bar.

I seem to remember this happening to several things while I was trying to get familiar with the app, but I cannot remember exactly what they are. The most easy to reproduce is the page settings found on the main page with all the image thumbnails.

**To Reproduce**
1. Open the app
2. Tap on the gear in the upper right above the thumbnails
3. Tap any of the settings (page mode, image grid, image list, image quality)
4. The last item in the list of options is always rendered behind the nav bar

For example, if I try to change the image grid setting using the method above, the options small and medium are accessible but large is behind the nav bar and cannot be tapped on.  

**Expected behavior**
Nothing should be rendered under/behind nav bar. Either the entire app window should be located above (x-y coord) the nav bar, or the navbar should auto hide if you want to use the fullscreen/immersive/edge-to-edge interface.

**Screenshots**
![Screenshot_20240619_113412_Boorusama](https://github.com/khoadng/Boorusama/assets/37705420/7bcac3e4-598e-4bd5-a955-7b1763fabea2)
![SmartSelect_20240619_113434_Boorusama](https://github.com/khoadng/Boorusama/assets/37705420/382b8ebc-1bd3-4a87-b740-172da9a4225d)
![Screenshot_20240619_113542_Boorusama](https://github.com/khoadng/Boorusama/assets/37705420/3184c977-1836-49ba-bc64-2621c8ff7502)

**Smartphone (please complete the following information):**
 - Device: tab s8 ultra
 - OS: Android 14
 - Version: 3.18.1

**Comment by khoadng** [comment]
I might miss something so feel free to reopen if you still having this issue.
