### ISSUE TITLE
Pull out side menu like a drawer

### ISSUE THREAD

**Issue by Kangaroux** [khoadng/Boorusama#433]
Swiping left when on the image list should pull out the side menu as a drawer. It's easy to misclick the drawer icon on a phone. The drawer icon is also not visible once you're in a search.

**Comment by khoadng** [comment]
This feature is already supported, but to make it easier to open the drawer, you may need to expand the swipe area. The Android back gesture can conflict with the drawer when Gesture Navigation is enabled. You can find and adjust this setting in the Accessibility options.
