### ISSUE TITLE
Saved searches doesn't seem to work.

### ISSUE THREAD

**Issue by duvjones** [khoadng/Boorusama#441]
**Describe the bug**
While logged in to danbooru, the "saved search" list seems to fail

**To Reproduce**
1. Configure to use danbooru.donmai.us
2. Login to a user account
3. Scroll down to "Saveed search"

**Smartphone (please complete the following information):**
 - Device: Galaxy Tab A (8", 2019)
 - OS: Android 11

There is something that I have noted, first off this only seems to affect danbooru.donmai.us... safebooru.donmai.us is unaffected by this. 
On a side note the saved `search` meta tag is also not working but only on danbooru.donmai.us.

**Comment by khoadng** [comment]
Saved search is not real-time, so you can check back after a few minutes to see the results. It works for me

**Comment by duvjones** [comment]
> Saved search is not real-time, so you can check back after a few minutes to see the results. It works for me.

That is what has me miffed, because it is working with the safebooru mirror but not danbooru itself.
I should also note that this error is happening on the two devices that I own... the Tab and a Moto One 5G Ace with Lineage OS 20 (Android 13)

> Also what kind of error? Can you send a screenshot?

Sure.... 
![Screenshot_20240725-112103_Trebuchet](https://github.com/user-attachments/assets/674f83d3-6ab3-4bb0-8c5e-26663596274e)

**Comment by khoadng** [comment]
I need more information.
Can you go to Settings > Debug logs and send it here?

**Comment by duvjones** [comment]
> I need more information. Can you go to Settings > Debug logs and send it here? Make sure to restart the app and go to the Saved search screen first.

Done

[boorusama_logs.txt](https://github.com/user-attachments/files/16380288/boorusama_logs.txt)
Oh and with the meta tags... this is the error that I have been getting. With the log...
![Screenshot_20240725-113235_Trebuchet](https://github.com/user-attachments/assets/51db060c-de0c-497b-bbfd-00bf6ffbda7f)
[boorusama_logs.txt](https://github.com/user-attachments/files/16380376/boorusama_logs.txt)

**Comment by khoadng** [comment]
There are numerous authorization errors. Did you create an API key with restricted permissions? The app expects a fully granted permission key. You can provide a minimal permissions key, but you will need to play around it to see what works and what doesn't.

**Comment by duvjones** [comment]
> There are a lot of authorization errors. Did you create an API key with restricted permissions? The app expects a fully granted permission key. You can provide a minimal permissions key, but you will need to play around it to see what works and what doesn't.

No, I didn't

**Comment by khoadng** [comment]
I use a single key for everything so it works fine. Can you create a brand new key with all permissions and try again? Leaving the permissions box empty will give all permissions.

**Comment by duvjones** [comment]
> I use a single key for everything and it works fine. Can you create a brand new key with all permissions and try again? Leaving the permissions box empty will give all permissions.

I have... still getting the same error.

**Comment by khoadng** [comment]
> > I use a single key for everything and it works fine. Can you create a brand new key with all permissions and try again? Leaving the permissions box empty will give all permissions.
> 
> I have... still getting the same error.

Maybe your login is incorrect then. Can you open the "Profile" screen? How about create a new profile for danbooru with the same information as the safe domain.

**Comment by duvjones** [comment]
> > > I use a single key for everything and it works fine. Can you create a brand new key with all permissions and try again? Leaving the permissions box empty will give all permissions.
> > 
> > 
> > I have... still getting the same error.
> 
> Maybe your login (username) is incorrect then. Can you open the 'Profile' screen and see if it displays the correct information? How about create a new profile for danbooru with the same information as the safe domain.

I don't know how.... I think that I might of missed something when typing in the website. Remade it in a new profile and it works.
The user name wasn't wrong but if I am to make a guess, I suspect that I might have used http than https.
I can tell you that in the old entry their wasn't a profile screen. It was just not in the list.

That said, thank you for the help. I have corrected this.
