### ISSUE TITLE
Bulk Download Folder Select is not working

### ISSUE THREAD

**Issue by lukilue** [khoadng/Boorusama#444]
**Describe the bug**
The folder select button is not working.

**To Reproduce**
1. Search for any tag
2. Click on Bulk Download or directly open bulk download and select a tag
3. When clicking on Folder Select, nothing happens
4. Also don't work with normal downloader -> settings -> folder

**Expected behavior**
Should open file explorer to select output folder

**Smartphone:**
 - Device: Samsung Galaxy
 - OS: Android

**Comment by khoadng** [comment]
what is your Android version?

**Comment by lukilue** [comment]
> what is your Android version?

Android 13
