### ISSUE TITLE
Multiple download selection hides video indicator

### ISSUE THREAD

**Issue by thebrokenfacade** [khoadng/Boorusama#447]
**Describe the bug**
When any search is done there is a video indicator on the thumbails of videos. This helps distinguish between animated media and static images without opening each item. 

When the user enters the select multiple mode for downloading, the video indicator is hidden. This is also true for indicators for galleries and AI posts.

**To Reproduce**
1. Conduct a search, or use the default results loaded when opening the app
2. Enter multi select mode by pressing and holding on an item and choosing 'select'
3. Media type indicators are hidden

**Expected behavior**
I am not sure if this is a bug or a limitation of how the app is built. It seems like the indicators for the type of media should not be hidden in multi-select mode.

Say I wanted to download just the pngs of a character from a specific artist to use as wallpapers. That artist also has videos of the same character so the thumbnails of the pngs and the thumbnails of the videos are indistinguishable from one another. Without the video indicator, I have no idea if I am adding a png or a video to the download list. I either have to add everything in the multi-select mode and delete just the videos after they are downloaded or select and download each png one at a time without the bulk download feature.

**Screenshots**
![Screenshot_20240823_094635_Boorusama](https://github.com/user-attachments/assets/35fb35cd-96e8-4e4c-8262-e7f79efb6b27)
![Screenshot_20240823_094659_Boorusama](https://github.com/user-attachments/assets/6744ff79-af56-4fa7-bfb9-a9ed53df8700)
![Screenshot_20240823_094722_Boorusama](https://github.com/user-attachments/assets/04ff1ab9-4f1f-42ce-81df-a7b3904a5661)

**Smartphone (please complete the following information):**
 - Device: Galaxy tab s8 ultra
 - OS: android 14
 - boorusama 3.20.0

**Comment by khoadng** [comment]
Looks like an oversight, it shouldn't be hidden.
