### ISSUE TITLE
Error when downloading MP4 video files

### ISSUE THREAD

**Issue by bhbobby** [khoadng/Boorusama#448]
Currently getting the following error from the debug log when it comes to MP4 files in bulk downloader. jpg and png files download fine, just get this error when downloading MP4 files

Download error: DioException [connection error]: The connection errored: No route to host. This indicates an error which most likely cannot be solved by the library.
Error: SocketException: No route to host (OS Error: No route to host. errno = 113)

Again, image files download fine, just get this error with MP4s and it only happened all of a sudden. Was not having any issues downloading video files before

**Comment by khoadng** [comment]
Does it happen only when downloading? Can you still play the video?

**Comment by bhbobby** [comment]
I cannot play the video either. And it's happening the same with other booru snatching apps as well. Maybe it's a website thing? Because it's only happening with rule 34
