### ISSUE TITLE
Issue when trying to use gelbooru

### ISSUE THREAD

**Issue by Lowen-Beehold** [khoadng/Boorusama#450]
**Describe the bug**
I followed the instructions put in my user name and copied the API key from the gelbooru.com website but I always get the "no data available" message. I tried both gelbooru 0.2 & 0.1 options but same result. Danbooru and other booru sites are loading fine it is just gelbooru. 
![Screenshot_2024-09-18-19-24-46-368_com degenk boorusama](https://github.com/user-attachments/assets/36cef872-59ba-4562-87f7-9b181db02673)

**Comment by khoadng** [comment]
Make sure to use your user ID instead of user name. For example 123456 instead my_username
