### ISSUE TITLE
Can't export favorites

### ISSUE THREAD

**Issue by adam-devel** [khoadng/Boorusama#453]
**Describe the bug**
A PathAccessException gets thrown when exporting favorites

**To Reproduce**
1. Go to 'Settings > Backup and Restore'
2. Of the list of items, choose "bookmarks" to export
3. Choose a folder in file picker

**Expected behavior**
Favorites get exported

**Screenshots**
![Screenshot_20241016_063642_Boorusama.jpg](https://github.com/user-attachments/assets/b2da846b-48d0-40cd-8405-a3346a54ab4b)

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Android 
 - Browser: isn't boorusama an app ? What does the browser have to do with it ?
 - Version: 3.20.0

**Additional context**
- the app is running on a work profile
- why is the app trying to access a .js file ?

**Comment by khoadng** [comment]
> isn't boorusama an app ? What does the browser have to do with it ?
It is from the default template. I will remove it.

> why is the app trying to access a .js file ?
It is a JSON file

> the app is running on a work profile
This might be the reason. The app has never been tested with this scenario. I will take a look later.

**Comment by adam-devel** [comment]
I was exporting into the main profile from the work profile, I apologize
I will close the issue
