### ISSUE TITLE
App does not support custom CAs

### ISSUE THREAD

**Issue by GGG-KILLER** [khoadng/Boorusama#463]
**Describe the bug**
I have a private booru instance that I run on my local network.
Said booru instance uses a self-signed certificate that is in a hierarchy of Root CA -> Intermediate CA -> Website CA.
I've installed booth the Root and Intermediate CAs on my phone's trust store.
Everything works fine from browser apps, however this app doesn't seem to use the certificate store from Android (or at least recognize the user-installed certificates).

**To Reproduce**
1. Have a booru instance with a private CA.
2. Add it to the app.
3. App doesn't recognize it.

**Expected behavior**
Booru works normally as the CAs have been installed into the phone and should be recognized as valid.

**Screenshots**
![Image showing that the app doesn't manage to make the request to the booru instance successfully](https://github.com/user-attachments/assets/f2a54d1a-cd92-47c3-a14d-125f63807df7)

**Desktop (please complete the following information):**
 - OS: N/A

**Smartphone (please complete the following information):**
 - Device: Moto G54 5G
 - OS: Android 14

**Additional context**
Nothing else to add.

**Comment by khoadng** [comment]
This is an issue with Dart/Flutter
https://github.com/dart-lang/sdk/issues/50435

I don't think they will support that anytime soon.

For now, there are a few ways to get this to work:
1. Add an option to ignore TLS verification for a specific profile. 
2. Add an option to choose a native HTTP client

Option 1 can be done quickly but very insecure
Option 2 is unstable and will break things because native HTTP client

**Comment by GGG-KILLER** [comment]
After looking a bit around the code, I believe the changes *should* be relatively simple, replacing the following:
https://github.com/khoadng/Boorusama/blob/a5869f767562571eaffbff4896a43c3fb4d449cb/lib/foundation/networking/dio.dart#L53-L61

With:
```diff
-  if (supportsHttp2) {
-    dio.httpClientAdapter = Http2Adapter(
-      ConnectionManager(
-        idleTimeout: const Duration(seconds: 30),
-      ),
-    );
-  }
+  dio.httpClientAdapter = NativeAdapter();
```

This `if` *shouldn't* be needed anymore as the native client will provide HTTP/2 (and even HTTP/3) support if available.
I'm unable to open a PR myself nor test this as I don't have a flutter setup nor ever used it before, so I apologize for not taking the initiative myself.
