### ISSUE TITLE
Going Blank After adding blacklist tag

### ISSUE THREAD

**Issue by Tryoskasen** [khoadng/Boorusama#466]
**Describe the bug**
When adding a blacklist tag, the page suddenly disappear

**To Reproduce**
As on the video

**Expected behavior**
the page not gone

**video**

https://github.com/user-attachments/assets/0777650f-5ab8-44ce-bc55-0c409f0ff08a

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
[log.txt](https://github.com/user-attachments/files/17891694/log.txt)

**Comment by khoadng** [comment]
What version are you using?

**Comment by Tryoskasen** [comment]
3.21.2
