### ISSUE TITLE
Title Bar Missing

### ISSUE THREAD

**Issue by Tryoskasen** [khoadng/Boorusama#469]
**Describe the bug**
window cannot drag and missing Title Bar Button
**To Reproduce**
as video

**Expected behavior**

**Video**

https://github.com/user-attachments/assets/468a2adb-b6ff-4f6b-b26e-28e292e68abd

 - OS: Windows 10
 - APP version :3.21.3

**Additional context**
Resize window working

**Comment by khoadng** [comment]
Is this on `dev` branch?

**Comment by khoadng** [comment]
Please test the latest updates from dev. I don't have access to a Windows machine right now, so I can't confirm if the issue has been fixed on Windows.

**Comment by Tryoskasen** [comment]
fixed
