### ISSUE TITLE
Feature request: More engines

### ISSUE THREAD

**Issue by satuputra796** [khoadng/Boorusama#470]
Hello, Satu here.

**I have a feature request:** Add more engines.

**What engines would you like added to Boorusama?**

- [Artbreeder](https://artbreeder.com)
- [ArtStation](https://artstation.com)
- [DeviantArt](https://deviantart.com)
- [Fur Affinity](https://furaffinity.net)
- [Furry Network](https://furrynetwork.com)
- [Pixiv](https://pixiv.net)
- [Rule34.gg](https://rule34.gg)
- [Sketchers United](https://sketchersunited.org)
- [Twitter/X](https://x.com)

**[Grabber](https://github.com/Bionus/imgbrd-grabber) has art platforms, why not use it?** Because it's an [outdated](https://github.com/Bionus/imgbrd-grabber/releases/tag/v7.12.2) app. It was last updated on May 15, and that's months ago. I could suggest a feature, but I feel afraid that the developer wouldn't respond/pay attention to it, seeing as some [issue posts](https://github.com/Bionus/imgbrd-grabber/issues) are still open.

**Comment by khoadng** [comment]
All of those sites are out of scope for this app. I only add support for sites that:

1) Have a history with Danbooru or are inspired by Danbooru, or
2) Are art-focused with an emphasis on searching using tags, and can either be open-source or provide a public API.

**Comment by satuputra796** [comment]
> All of those sites are out of scope for this app. I only add support for sites that:
> 
> 1. Have a history with Danbooru or are inspired by Danbooru, or
> 2. Are art-focused with an emphasis on searching using tags, and can either be open-source or provide a public API.

So, do you only add support for booru sites? /genq /nm /nf /nav

**Comment by khoadng** [comment]
Yep it's literary in the app's name. Not everything is supported, as I handle it on a case-by-case basis
