### ISSUE TITLE
Missed translations keys

### ISSUE THREAD

**Issue by lesh6295-png** [khoadng/Boorusama#80]
I noticed than part of text in application dosent have a keys in `en.json`. Can you add them for better translating experience?

**Comment by lesh6295-png** [comment]
For explame:
![IMG_20221015_162725.jpg](https://user-images.githubusercontent.com/81479253/195989484-3d1feec1-cf68-4b71-b122-f7718d22832b.jpg)![IMG_20221015_162637.jpg](https://user-images.githubusercontent.com/81479253/195989494-dbd97465-a8b3-462b-b50d-6dd869b742e6.jpg)![IMG_20221015_162612.jpg](https://user-images.githubusercontent.com/81479253/195989503-677d07ca-ce83-4fed-8b6e-cdf1873e416f.jpg)

**Comment by khoadng** [comment]
I am guilty of this for being lazy... 
Sure i'll localize those keys as well

**Comment by khoadng** [comment]
I think i have extracted most of the keys to the translation files. So i'm going to go ahead and close this ticket.
Feel free to reopen it if you found any missing keys.
